FROM node:20-alpine

WORKDIR /app

# Install yarn
RUN npm install -g yarn

# Configure yarn for better network handling
RUN yarn config set network-timeout 600000

COPY package*.json ./
RUN yarn install --verbose
COPY . .

RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]